# Generated by Django 4.2.4 on 2023-10-23 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_tools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(default='studentavar.png', upload_to='students')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('roll', models.CharField(max_length=6, unique=True)),
                ('registration_number', models.CharField(max_length=6, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=11, null=True)),
                ('guardian_mobile', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ac_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_tools.academicsession')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_tools.department')),
                ('semester', models.ForeignKey(default='1st', on_delete=django.db.models.deletion.CASCADE, to='admin_tools.semester')),
            ],
            options={
                'ordering': ['semester', 'roll', 'registration_number'],
            },
        ),
    ]
