# Generated by Django 5.0.7 on 2024-09-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('flight_no', models.CharField(max_length=100)),
                ('starting_from', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('food_supply', models.BooleanField()),
                ('price', models.IntegerField()),
                ('seats', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
